CREATE DATABASE EMEGA_MART;

CREATE TABLE `USER_LOGIN` (
  `USER_NAME` INT(11) NOT NULL,
  `USER_PASSWORD` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `PROD_CATEGORIES` (
  `CATEGORY_ID` INT(11) NOT NULL,
  `CATEGORY` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` INT(11) NOT NULL,
  `CATEGORY_ID` INT(11) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL,
  `DESCRIPTION` VARCHAR(100) DEFAULT NULL,
  `PRICE` INT(11) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  KEY `CATEGORY_ID` (`CATEGORY_ID`),
  CONSTRAINT `PRODUCTS_CAT_FK` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `PROD_CATEGORIES` (`CATEGORY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `PROD_ORDER` (
  `ORDER_ID` INT(11) NOT NULL DEFAULT '0',
  `CONTACT_NAME` VARCHAR(100) NOT NULL,
  `DELIVERY_ADDRESS` VARCHAR(100) NOT NULL,
  `CC_NAME` VARCHAR(30) NOT NULL,
  `CC_NUMBER` INT(11) NOT NULL,
  `CC_EXPIRY_DATE` DATE DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE `PROD_ORDER_DETAILS` (
  `ORDER_DTL_ID` INT(11) NOT NULL,
  `ORDER_ID` INT(11) NOT NULL,
  `PRODUCT_ID` INT(11) NOT NULL,
  `ORDER_QTY` INT(11) NOT NULL,
  `ORDER_PRICE` INT(11) NOT NULL,
  PRIMARY KEY (`ORDER_DTL_ID`,`ORDER_ID`),
  CONSTRAINT `ORDER_PROD_FK` FOREIGN KEY (`ORDER_ID`) REFERENCES `PROD_ORDER` (`ORDER_ID`),
  CONSTRAINT `PROD_ORDERDTL_FK` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS` (`PRODUCT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


